# =========================
# APP
# =========================
spring.application.name=Rycus-backend
server.forward-headers-strategy=framework

# =========================
# DATABASE (LOCAL FALLBACK)
# =========================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d542ul0gjchc73fjjgt0-a.virginia-postgres.render.com:5432/rycus_db?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:rycusdb_2efu_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:38iTrt7jRuVaEJsCJun3aroKdHEeEeJK}

spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# FRONTEND / APP URL
# =========================
rycus.app.url=${RYCUS_APP_URL:https://rycus.app}

# =========================
# FILE UPLOAD
# =========================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-swallow-size=10MB

# =========================
# STRIPE
# =========================
stripe.secret.key=${STRIPE_SECRET_KEY:}
stripe.price.id=${STRIPE_PRICE_ID:}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET:}
